version: '3.7'

services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    ports:
      - 8080:8080
    command: -P . -a . /data/packages
    restart: always
    volumes:
      - pypi-server:/data

volumes:
  pypi-server:
